# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: diffraction.cam
subtitle: Visible Diffraction for Digital Cameras
logo: https://photos.smugmug.com/photos/i-zwKSJCZ/0/8a283f55/O/i-zwKSJCZ.jpg
name: "Rob Shea" #copyright
email: diff@590.mozmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: https://diffraction.cam

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "mint", "neon", "plum", "sunrise"
lang: "en"
locale: "en-US"
show_date: true # in posts
date_format: "%Y-%B-%d" # https://www.shortcutfoo.com/app/dojos/ruby-date-format-strftime/cheatsheet
timezone: America/Detroit
markdown: kramdown

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-MCPPLEDRRY"
    anonymize_ip: false # default

#google:
#  search_engine_id: 60c6033163bd149ae

head_scripts:
  https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML
#  - https://code.jquery.com/jquery-3.2.1.min.js
#  - /assets/js/your-custom-head-script.js
footer_scripts:
  /assets/js/main.js
#  - https://code.jquery.com/jquery-3.2.1.min.js
#  - /assets/js/your-custom-head-script.js

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: ["_pages"]

footer:
  links:
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/c/RobSheaPhotography"
    - label: "Blog"
      icon: "fas fa-blog"
      url: "https://blog.robsheaphotography.com"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/rob_shea/"
    - label: "Vero"
      icon: fas fa-photo-video"
      url: "https://vero.co/robshea"
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: "https://www.facebook.com/robsheaphotography"
    - label: "TikTok"
      icon: "fab fa-tiktok"
      url: "https://www.tiktok.com/@rob.shea"
    - label: "Gallery"
      icon: "fas fa-image"
      url: "https://www.robsheaphotography.com"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:diff@590.mozmail.com?subject=diffraction.cam"
